/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const ConsultantProfile = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getConsultantProfile' : IDL.Func([], [ConsultantProfile], ['query']),
  'getServicesByCategory' : IDL.Func([], [IDL.Vec(Service)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const ConsultantProfile = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getConsultantProfile' : IDL.Func([], [ConsultantProfile], ['query']),
    'getServicesByCategory' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };